# Generated by Django 4.2 on 2023-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('awards_link', models.CharField(max_length=100)),
                ('category_and_time', models.CharField(max_length=30)),
            ],
        ),
    ]
