# Generated by Django 4.2 on 2023-05-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work/')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('project_link', models.CharField(max_length=100)),
            ],
        ),
    ]
