# Generated by Django 4.2 on 2023-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients/')),
                ('client_name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
