# Generated by Django 4.2 on 2023-05-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_Info',
            new_name='SiteInfo',
        ),
    ]
