# Generated by Django 4.2 on 2023-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_site_info_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='costomers_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='feedback_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='lines_of_code_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='projects_desc',
            field=models.TextField(),
        ),
    ]
