# Generated by Django 4.2 on 2023-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_siteinfo_costomers_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='contact_desc',
            field=models.TextField(max_length=300),
        ),
    ]
