# Generated by Django 4.2 on 2023-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_mycv'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycv',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
